routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('categories', 'CategoryController');

Route::get('articles/{category?}', 'ArticleController@index')->name('articles');
Route::get('/rss/update', 'RetrievalController@retrieve_articles')->name('retrieve');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'category_id','title', 'link', 'description', 'guid', 'publish_date'
    ];

    protected $dates = [
        'publish_date',
    ];

    public function category()
    {
        return $this->belongsTo('App\Category');
    }
}

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name','path', 'active'
    ];

    public function articles()
    {
        return $this->hasMany('App\Article');
    }
}

app/Retrieval.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Retrieval extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;
use App\Category;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($category=NULL)
    {        
        if($category) {
            $category_record = Category::where('path', $category)->first();
            $data['articles'] = Article::where('category_id', $category_record->id)->get();
            $data['category'] = $category_record;
        } else {
            $data['articles'] = Article::all();            
        }
        

        return view('article.index', $data);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Article;
use DB;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $data['categories'] = DB::table('categories')->selectRaw("categories.*,count(articles.id) as total")->where('active', true)->join('articles', 'articles.category_id', '=', 'categories.id')->groupBy('categories.id')->get();                
        return view('category.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'path'=>'required',
        ]);

        $category = new Category([
            'name' => $request->get('name'),
            'path' => $request->get('path'),
            'active' => true,
        ]);
        $category->save();
        return redirect('/categories')->with('success', 'Category saved!');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use App\Category;
use View;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

     public function __construct() {
     	$categories = Category::where('active', 1)->get();
       	View::share ( 'categories', $categories );
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/RetrievalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Willvincent\Feeds;
use App\Category;
use App\Article;
use App\Retrieval;

class RetrievalController extends Controller
{
    public function retrieve_articles()
    {
    	$categories = Category::all();
    	$data['results'] = '';
    	foreach ($categories as $category) {
	    	$url = env("RSS_BASE") . $category->path . '/rss.xml';
	    	$feed = \Feeds::make($url);
		    $items = $feed->get_items();
		    $records = 0;

		    foreach($items as $item) {
		        $title = $item->get_title();
		        $link = $item->get_permalink();
		        $description = $item->get_description();
		        if(!$description) {
		        	$description = '';
		        }
		        $guid_array = $item->get_item_tags('','guid');
		        $date_array = $item->get_item_tags('','pubDate');
		        $guid =  $guid_array[0]['data'];
		        $date =  $date_array[0]['data'];

		        //Check if Exists already
		        $existing = Article::where('guid', $guid)->first();	        
		        
		        if(!$existing) {
		        	try {
		        		$article = new Article;
			        	$article->category_id = $category->id;
			        	$article->title = $title;
			        	$article->link = $link;
			        	$article->description = $description;
			        	$article->guid = $guid;
			        	$article->publish_date = date('Y-m-d', strtotime($date));
			        	$article->save();	
			        	$records++;
		        	} catch (\Exception $e) {
					    return $e->getMessage();
					}
		        }
		    }

		    //Update retrieval log
	        $retrieval = new Retrieval;
	        $retrieval->category_id = $category->id;
	        $retrieval->new_records = $records;
	        $retrieval->requested_by = 'Authorized User';
	        $retrieval->save();
	        
	        $data['results'] .= $records . ' articles added for ' . $category->name . '<br/>';
	        
		}
		return view('retrieval.completed', $data);
	}
}

resources/views/article/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Articles</h1>
    @if(isset($category))
    	<h3>{{$category->name}}</h3>
    @endif
  <div>
  @foreach($articles as $article)
  	<p>
  		<a href="{{$article->link}}" target="_blank">{{ $article->title }}</a> ({{$article->publish_date->format('m/d/Y')}})<br />
  		{{$article->description}}
	</p>
  @endforeach
  </div>
</div>
</div>
@endsection

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a Category</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('categories.store') }}">
          @csrf
          <div class="form-group">    
              <label for="name">Name:</label>
              <input type="text" class="form-control" name="name"/>
          </div>

          <div class="form-group">    
              <label for="path">Name:</label>
              <input type="text" class="form-control" name="path"/>
          </div>

                                 
          <button type="submit" class="btn btn-primary-outline">Add Category</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Categories</h1>
  <div>
  @foreach($categories as $category)
  	<a href="/articles/{{$category->path}}">{{ $category->name }} ({{$category->total}})</a> <br />
  @endforeach
  </div>
</div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">OSM</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Categories
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @if (Auth::check())
                                <a class="dropdown-item" href="/categories/create">Add Category</a>
                                <a class="dropdown-item" href="/rss/update">Update Articles</a>
                            @endif
                            <a class="dropdown-item" href="/categories">View Categories</a>
                            @if(isset($categories))
                            <div class="dropdown-divider"></div>
                                @foreach ($categories as $category)
                                    <a class="dropdown-item" href="/articles/{{$category->path}}">{{$category->name}}</a>
                                @endforeach
                            @endif
                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/retrieval/completed.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Categories</h1>
  <div>
  	{!!$results!!}
  </div>
</div>
</div>
@endsection